
name: "atique Terraform Pipeline123456"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraformjob:
    name: Terraformjobtest12345
    runs-on: dhondhu-khilji

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Verify Terraform
        run: terraform -version
        shell: pwsh

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Terraform Plan (detailed)
        run: terraform plan -input=false -out=tfplan.out  
        working-directory: environments/dev

      - name: Show Terraform Plan
        run: terraform show -no-color tfplan.out
